/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metnume;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge M
 */
public class DatosAgrupados extends javax.swing.JFrame {

    /**
     * Creates new form Meet
     */
    public DatosAgrupados() {
        initComponents();
        start();
        setLocationRelativeTo(null);
    }
    
    int counter, total;
    double [] submited = new double[45];
    double [] era;
    int [] frecuencia = new int[45];
    double media, sumatoria, varianza, xifi, resultadoera, resultadoerr;
    String erra, valor, frecu, errr, xf, mediaa;
    DecimalFormat DF = new DecimalFormat("#.00");
    DecimalFormat FD = new DecimalFormat("#.000");
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Valores Agrupados");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Media");
        jLabel2.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(85, 14));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Varianza");
        jLabel3.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(85, 14));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Error Absoluto");
        jLabel4.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(85, 14));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel9.setText("   ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 30, 20));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Error Relativo");
        jLabel1.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(85, 14));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Σ(Xi*fi)");
        jLabel20.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel20.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel20.setPreferredSize(new java.awt.Dimension(85, 14));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jScrollPane2.setHorizontalScrollBar(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("jLabel8");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 70, 570));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("jLabel12");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel12.setMaximumSize(new java.awt.Dimension(69, 14));
        jLabel12.setMinimumSize(new java.awt.Dimension(69, 14));
        jLabel12.setPreferredSize(new java.awt.Dimension(69, 14));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 570));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("jLabel13");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel13.setMaximumSize(new java.awt.Dimension(69, 14));
        jLabel13.setMinimumSize(new java.awt.Dimension(69, 14));
        jLabel13.setPreferredSize(new java.awt.Dimension(69, 14));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 560));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel5");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setMaximumSize(new java.awt.Dimension(69, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(69, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(69, 14));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 560));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("jLabel19");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel19.setMaximumSize(new java.awt.Dimension(69, 14));
        jLabel19.setMinimumSize(new java.awt.Dimension(69, 14));
        jLabel19.setPreferredSize(new java.awt.Dimension(69, 14));
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 570));

        jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 430, 290));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("(Xi-Media)²f");
        jLabel16.setMaximumSize(new java.awt.Dimension(75, 14));
        jLabel16.setMinimumSize(new java.awt.Dimension(75, 14));
        jLabel16.setPreferredSize(new java.awt.Dimension(75, 14));
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 8, -1, -1));

        jLabel14.setText("Error Absoluto");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 8, -1, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Xi * fi");
        jLabel18.setMaximumSize(new java.awt.Dimension(69, 14));
        jLabel18.setMinimumSize(new java.awt.Dimension(69, 14));
        jLabel18.setPreferredSize(new java.awt.Dimension(69, 14));
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 8, -1, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Frecuencia");
        jLabel11.setMaximumSize(new java.awt.Dimension(69, 14));
        jLabel11.setMinimumSize(new java.awt.Dimension(69, 14));
        jLabel11.setPreferredSize(new java.awt.Dimension(69, 14));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 8, -1, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Valor");
        jLabel10.setMaximumSize(new java.awt.Dimension(69, 14));
        jLabel10.setMinimumSize(new java.awt.Dimension(69, 14));
        jLabel10.setPreferredSize(new java.awt.Dimension(69, 14));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 8, 430, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Clean");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, -1));

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jCheckBox1.setText("Frecuencia");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextField1.setText("jTextField1");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, -1));

        jSpinner1.setName(""); // NOI18N
        jSpinner1.setValue(1
        );
        jSpinner1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jSpinner1MouseWheelMoved(evt);
            }
        });
        jPanel4.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 50, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, 160));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Dv. Estandar");
        jLabel22.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel22.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel22.setPreferredSize(new java.awt.Dimension(85, 14));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Total Datos");
        jLabel24.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel24.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel24.setPreferredSize(new java.awt.Dimension(85, 14));
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("jLabel25");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/home_1.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/black-texture-wallpaper-On-wallpaper-hd.jpg"))); // NOI18N
        jLabel26.setText("jLabel26");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 660, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Integer.parseInt(jSpinner1.getValue().toString())<=0 || jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Entrada no valida", "Error", JOptionPane.ERROR_MESSAGE);
            jSpinner1.setValue(1);
            jTextField1.requestFocus();
        }
        else{
            submited[counter]=Double.parseDouble(jTextField1.getText());
            if (jCheckBox1.isSelected()) {
                frecuencia[counter]=Integer.parseInt(jSpinner1.getValue().toString());
            }
            else{
                frecuencia[counter]=1;
            }
            valor="<html><body>"+String.valueOf(submited[counter])+"<br>"+valor+"</body></html>";
            frecu="<html><body>"+String.valueOf(frecuencia[counter])+"<br>"+frecu+"</body></html>";
            xf="<html><body>"+String.valueOf(DF.format(submited[counter]*frecuencia[counter]))+"<br>"+xf+"</body></html>";
            
            xf=xf.replace("null", "");
            valor=valor.replace("null", "");
            frecu=frecu.replace("null", "");

            if (xf.startsWith("<html><body>,") || xf.startsWith("<html><body>-,")) {
                xf=xf.replace(",", "0,");
            }

            jLabel12.setText(valor);
            jLabel13.setText(frecu);
            jLabel19.setText(xf);

            System.out.print(counter+"    ");
            System.out.print(submited[counter]+"    ");
            System.out.println(frecuencia[counter]+"    ");

            jCheckBox1.setEnabled(false);
            jTextField1.requestFocus();
            jTextField1.setText("");
            jSpinner1.setValue(1);
            counter++;

            jButton2.setEnabled(true);
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // CALCULAR
        media();
        xifi();
        varianza();
        errorA();
        errorR();
        
        jTextField1.setEnabled(false);
        jCheckBox1.setEnabled(false);
        jButton2.setEnabled(false);
        jSpinner1.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jSpinner1.isEnabled()) {
            jSpinner1.setEnabled(false);
        }
        else{
            jSpinner1.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        start();
        jTextField1.setEnabled(true);
        for (int i = 0; i < counter; i++) {
            submited[i]=0;
            frecuencia[i]=0;
            era[i]=0;
        }
        counter=0;
        total=0;
        erra=null;
        errr=null;
        valor=null;
        frecu=null;
        mediaa=null;
        sumatoria=0;
        media=0;
        varianza=0;
        resultadoera=0;
        resultadoerr=0;
        xifi=0;
        xf=null;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // Key released
        String digit = jTextField1.getText();
        char last=0;
        if (digit.isEmpty()) {
            //Xd
        }
        else{
            try {
                    last=digit.charAt(digit.length()-1);
                    Integer.parseInt(String.valueOf(last));
                    
            } catch (NumberFormatException nfe){
                if (String.valueOf(last).equals(".") || String.valueOf(last).equals("-")) {
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Entrada no valida", "Error", JOptionPane.ERROR_MESSAGE);
                    String write = digit.substring(0, digit.length()-1);
                    jTextField1.setText(write);
                } 
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jSpinner1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jSpinner1MouseWheelMoved
        // TODO add your handling code here:
        int notches = evt.getWheelRotation();
        if (notches < 0) {
            jSpinner1.setValue(jSpinner1.getNextValue());
        }
        if (notches > 0 && !jSpinner1.getPreviousValue().equals(0)){
            jSpinner1.setValue(jSpinner1.getPreviousValue());
        }
            
    }//GEN-LAST:event_jSpinner1MouseWheelMoved

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Main JM = new Main();
        JM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    public void media(){
        double med=0;
        for (int i = 0; i < counter; i++) {
            med=med+(submited[i]*frecuencia[i]);
        }
        for (int i = 0; i < counter; i++) {
            total=total+frecuencia[i];
        }
        media=med/total;
        mediaa=DF.format(media);
        if (mediaa.startsWith(",")) {
            mediaa=mediaa.replace(",", "0,");
        }
        jLabel6.setText(mediaa);
        jLabel25.setText(total+"");
    }
    
    public void varianza(){
        double [] xmed = new double[counter];
        double [] xmed2 = new double[counter];
        double desv;
        String vari, desvest, xifif="";
        
        for (int i = 0; i < counter; i++) {
            xmed[i]=submited[i]-media;
        }
        
        for (int i = 0; i < counter; i++) {
            xmed2[i]=xmed[i]*xmed[i]*frecuencia[i];
            xifif="<html><body>"+String.valueOf(DF.format(xmed2[i]))+"<br>"+xifif+"</body></html>";
            sumatoria=sumatoria+xmed2[i];
        }
        xifif=xifif.replace("null", "");
        
        if (xifif.contains("<html><body>,")) {
            xifif=xifif.replace(">,", ">0,");
        }
        
        varianza=sumatoria/(total);
        desv=Math.sqrt(varianza);
        vari=FD.format(varianza);
        desvest=FD.format(desv);
        if (vari.startsWith(",")) {
            vari=vari.replace(",", "0,");
        }
        if (desvest.startsWith(",")) {
            desvest=desvest.replace(",", "0,");
        }
        jLabel5.setText(xifif);
        jLabel7.setText(vari);
        jLabel23.setText(desvest);
    }
    
    public void errorA(){
        
        era = new double[counter];
        double sumera=0;
        String result;
        for (int i = 0; i < counter; i++) {
            era[i]=Math.abs((xifi/total)-submited[i]);
            erra="<html><body>"+String.valueOf(DF.format(era[i]))+"<br>"+erra+"</body></html>";
            sumera=sumera+era[i];
        }
        
        resultadoera=sumera/total;
        
        erra=erra.replace("null", "");
        
        if (erra.contains("<html><body>,")) {
            erra=erra.replace(">,", ">0,");
        } 
        if (erra.contains("<html><body>-,")) {
            erra=erra.replace(">-,", ">-0,");
        }
        
        result=FD.format(resultadoera);
        if (result.startsWith(",")) {
            result=result.replace(",", "0,");
        }
        jLabel8.setText(erra);
        jLabel15.setText(result);
        /*for (int i = 0; i < counter; i++) {
            era[i]=(media-submited[i])*(media-submited[i]);
            erra="<html><body>"+String.valueOf(DF.format(era[i]))+"<br>"+erra+"</body></html>";
            sumera=sumera+Math.abs(era[i]);
        }
        erra=erra.replace("null", "");
        
        if (erra.contains("<html><body>,")) {
            erra=erra.replace(">,", ">0,");
        } 
        if (erra.contains("<html><body>-,")) {
            erra=erra.replace(">-,", ">-0,");
        }
        
        jLabel8.setText(erra);
        
        resultado=sumera/total;
        result=DF.format(resultado);
        if (result.startsWith(",")) {
            result=result.replace(",", "0,");
        }
        jLabel15.setText(mediaa+" ± "+result);*/
    }
    
    public void errorR(){
        String result;
        resultadoerr=resultadoera/(xifi/total);
        
        result=FD.format(resultadoerr);
        if (result.startsWith(",")) {
            result=result.replace(",", "0,");
        }
        
        jLabel17.setText(result);
        
        /*
        double [] err = new double [counter];
        double sumerr=0;
        String errorr="",sumerrs="";
        
        for (int i = 0; i < counter; i++) {
            err[i]=((Math.abs(era[i]))/media)*100;
            errorr="<html><body>"+String.valueOf(DF.format(err[i]))+"<br>"+errorr+"</body></html>";
            sumerr=sumerr+err[i];
        }
        System.out.println("sumerr: "+sumerr);
        errorr=errorr.replace("null", "");
        sumerrs=DF.format(sumerr);
        if (errorr.contains("<html><body>,")) {
            errorr=errorr.replace(">,", ">0,");
        }
        
        jLabel17.setText(sumerrs);*/
    }
    
    public void xifi(){
        String xfi;
        for (int i = 0; i < counter; i++) {
            xifi=xifi+(submited[i]*frecuencia[i]);
        }
        xfi=DF.format(xifi);
        if (xfi.startsWith(",")){
            xfi=xfi.replace(",", "0,");
        }
        jLabel21.setText(xfi);
    }
    
    private void start(){
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");
        jLabel12.setText("");
        jLabel13.setText("");
        jLabel15.setText("");
        jLabel17.setText("");
        jLabel19.setText("");
        jLabel21.setText("");
        jLabel23.setText("");
        jLabel25.setText("");
        jTextField1.setText("");
        jButton2.setEnabled(false);
        jSpinner1.setEnabled(true);
        jCheckBox1.setEnabled(false);
        jCheckBox1.setSelected(true);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Resources/x2-symbol-of-a-letter-and-a-number-subscript.png"));
        return retValue;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosAgrupados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
